#!/bin/bash

PICTURE=$(mktemp /tmp/i3lock.XXXXXX.png)
BLUR="5x4"

if scrot -z "$PICTURE" && convert "$PICTURE" -blur "$BLUR" "$PICTURE"; then
    i3lock -i "$PICTURE"
    rm -f "$PICTURE"
else
    rm -f "$PICTURE"
    i3lock -c 282c34
fi
