#!/bin/bash
# Power menu via rofi

typeset -A menu
menu=(
  [" Shutdown"]="systemctl poweroff"
  [" Reboot"]="systemctl reboot"
  [" Suspend"]="systemctl suspend"
  [" Hibernate"]="systemctl hibernate"
  [" Lock"]="~/.config/i3/scripts/blur-lock"
  [" Logout"]="i3-msg exit"
  [" Cancel"]=""
)

selection="$(printf '%s\n' "${!menu[@]}" | sort | rofi -dmenu -i -lines ${#menu[@]} -p "Power:" -theme ~/.config/rofi/powermenu.rasi)"

if [[ -n "$selection" ]]; then
    i3-msg -q "exec --no-startup-id ${menu[$selection]}"
fi
