#!/bin/bash

# Toggle default audio sink between Speaker and Headphones
SPEAKER="alsa_output.pci-0000_00_1f.3-platform-sof_sdw.HiFi__Speaker__sink"
HEADPHONES="alsa_output.pci-0000_00_1f.3-platform-sof_sdw.HiFi__Headphones__sink"

CURRENT=$(pactl get-default-sink)

if [ "$CURRENT" = "$SPEAKER" ]; then
    pactl set-default-sink "$HEADPHONES"
    notify-send -t 2000 "Audio" "Switched to Headphones"
else
    pactl set-default-sink "$SPEAKER"
    notify-send -t 2000 "Audio" "Switched to Speaker"
fi
