#!/bin/bash
# Launch chat apps (tabbed) on workspace 10

sleep 2

i3-msg 'workspace number 10'

Telegram &

# Wait for Telegram window to appear before setting layout (30s timeout)
tries=0
while ! i3-msg -t get_tree | jq -e '.. | objects | select(.window_properties?.class == "TelegramDesktop")' &>/dev/null; do
    sleep 0.5
    tries=$((tries + 1))
    (( tries >= 60 )) && break
done

i3-msg 'layout tabbed'

signal-desktop-beta &
slack &
