#!/bin/bash
# Launch chat apps (tabbed) on workspace 10

sleep 2

i3-msg 'workspace number 10'

telegram-desktop &

# Wait for Telegram window to appear before setting layout
i3-msg -t subscribe '["window"]' > /dev/null

i3-msg 'layout tabbed'

signal-desktop &
slack &
